# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase Pods for ios
  pod 'Firebase/Analytics'
  #pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  #pod 'Firebase/Functions'
  #pod 'Firebase/Messaging'
  #pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
  #pod 'Firebase/Performance'
  #pod 'Firebase/RemoteConfig'

  # Additional library for Firestore with Swift Codable support
  pod 'FirebaseFirestoreSwift'
  pod 'Resolver'

end
